language: julia

os:
  - linux
  - osx

julia:  
  - 1.3
  - nightly

branches:
  only:
    - master
    - /^release-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

after_success:
  - if [ -f test/quietly.log ]; then cat test/quietly.log; fi
  - if [[ $TRAVIS_JULIA_VERSION = 1.1 ]] && [[ $TRAVIS_OS_NAME = linux ]]; then
      julia --project=coverage/ -e 'using Pkg; Pkg.instantiate(); using Coverage; Codecov.submit(Codecov.process_folder());Coveralls.submit(process_folder())';      
    fi

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Test"
       - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
       - travis_wait 30 julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build(); Pkg.test( ; coverage=true)';
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl      
      after_success: skip    

notifications:
  email: false
