site_name:        ClimateTools.jl
repo_url:         https://github.com/Balinus/ClimateTools.jl/
edit_uri:        https://github.com/Balinus/ClimateTools./blob/master/docs/src/index.md
site_description: Collection of commonly-used tools in Climate Science
site_author:      Balinus

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: 'index.md'
  # - Getting started: 'gettingstarted.md'
  # - Climate indices: 'indices.md'
  # - Examples: 'examples.md'
